### ISSUE TITLE
Getting crashed when using --context option

### ISSUE THREAD

**Issue by ddding** [JFLarvoire/the_silver_searcher#4]
When I use --context or --before option, it will get crashed. 
![default](https://user-images.githubusercontent.com/21052284/39090998-2180d77e-461e-11e8-8cf4-c6ec3ee281c8.png)

**Comment by JFLarvoire** [comment]
Bug fixed in the new release 2.2.1-Windows  
https://github.com/JFLarvoire/the_silver_searcher/releases/tag/2.2.1-Windows
